Repository navikt/aksel, pull requests merged in 2022-03, with the labels that each got.

#1445 Table sort
  .storybook/main.js
  .storybook/preview.js
  .storybook/public/mockServiceWorker.js
  @navikt/core/css/button.css
  @navikt/core/css/table.css
  @navikt/core/react/package.json
  @navikt/core/react/src/button/Button.tsx
  @navikt/core/react/src/button/button.stories.tsx
  @navikt/core/react/src/menu/Menu.tsx
  @navikt/core/react/src/table/ColumnHeader.tsx
  @navikt/core/react/src/table/DataCell.tsx
  @navikt/core/react/src/table/HeaderCell.tsx
  @navikt/core/react/src/table/Table.tsx
  @navikt/core/react/src/table/stories/people.json
  @navikt/core/react/src/table/stories/table-async.stories.tsx
  @navikt/core/react/src/table/stories/table-hot.stories.tsx
  @navikt/core/react/src/table/stories/table.stories.tsx
  @navikt/internal/react/src/copy-to-clipboard/CopyToClipboard.tsx
  package.json
  yarn.lock
Labels: Ready for review

#1382 [FEATURE] Nytt søkefelt
  @navikt/core/css/form/index.css
  @navikt/core/css/form/search-field.css
  @navikt/core/css/form/search.css
  @navikt/core/css/form/text-field.css
  @navikt/core/react/src/form/index.ts
  @navikt/core/react/src/form/search-field/SearchField.tsx
  @navikt/core/react/src/form/search-field/SearchFieldButton.tsx
  @navikt/core/react/src/form/search-field/SearchFieldClearButton.tsx
  @navikt/core/react/src/form/search-field/SearchFieldInput.tsx
  @navikt/core/react/src/form/search-field/index.ts
  @navikt/core/react/src/form/search-field/stories/search-field-example.tsx
  @navikt/core/react/src/form/search-field/stories/search-field.stories.mdx
  @navikt/core/react/src/form/search-field/stories/search-field.stories.tsx
  @navikt/core/react/src/form/search/Search.tsx
  @navikt/core/react/src/form/search/SearchButton.tsx
  @navikt/core/react/src/form/search/index.ts
  @navikt/core/react/src/form/search/search.stories.tsx
  @navikt/core/react/src/form/search/useSearch.ts
  @navikt/core/react/src/util/index.ts
  yarn.lock
Labels: universell utforming, new ✨, Ready for review

#1450 [FIX] parentElement prop på Modal
  @navikt/core/react/src/modal/Modal.tsx
Labels: Ready for review

#1452 [FIX] onSubmit kjører onSearch callback i `Search`
  @navikt/core/react/src/form/search/Search.tsx
  @navikt/core/react/src/form/search/SearchButton.tsx
Labels: Ready for review

#1454 [FIX] Search: form -> div
  @navikt/core/react/src/form/search/Search.tsx
  @navikt/core/react/src/form/search/SearchButton.tsx
Labels: Ready for review

#1455 [FIX] Bedre width for search
  @navikt/core/css/form/search.css
  @navikt/core/react/src/form/search/search.stories.tsx
Labels: Ready for review

#1407 Helptext uu fix
  @navikt/core/css/help-text.css
  @navikt/core/react/src/help-text/HelpText.tsx
  @navikt/core/react/src/help-text/help-text.stories.tsx
  @navikt/core/react/src/help-text/stories/help-text.stories.mdx
  @navikt/core/react/src/help-text/stories/help-text.stories.tsx
Labels: Ready for review

#1458 [FIX] Oppdatert ikon-template, SSR-safe uuid
  @navikt/core/icons/package.json
  @navikt/core/icons/template.js
  @navikt/core/icons/tsconfig.json
  @navikt/core/icons/util/useId.ts
Labels: Ready for review

#1460 update icons from Figma
  @navikt/core/icons/meta.json
  @navikt/core/icons/svg/Attachment.svg
  @navikt/core/icons/svg/AttachmentFilled.svg
  @navikt/core/icons/svg/EmailOpen.svg
  @navikt/core/icons/svg/EmailOpenFilled.svg
  @navikt/core/icons/svg/EmailOpened.svg
  @navikt/core/icons/svg/EmailOpenedFilled.svg
  @navikt/core/icons/svg/Teddy.svg
  @navikt/core/icons/svg/TeddyFilled.svg
  @navikt/core/icons/svg/UpDown.svg
  @navikt/core/icons/svg/UpDownFilled.svg
  @navikt/core/icons/svg/Warning.svg
  @navikt/core/icons/svg/WarningFilled.svg
Labels: Ready for review

#1461 [fix] up-down for default sort state
  @navikt/core/react/src/table/ColumnHeader.tsx
Labels: Ready for review

#1447 [FIX] Alert styling og ikoner
  @navikt/README.md
  @navikt/core/css/alert.css
  @navikt/core/react/src/alert/Alert.tsx
Labels: Ready for review

#1457 [FIX] Endringsforslag Pagination
  @navikt/core/css/pagination.css
  @navikt/core/react/src/pagination/Pagination.tsx
  @navikt/core/react/src/pagination/pagination.stories.tsx
Labels: Ready for review

#1429 [FIX] New/stepper
  @navikt/core/css/index.css
  @navikt/core/css/stepper.css
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/step-indicator/stories/step-indicator.stories.mdx
  @navikt/core/react/src/stepper/Step.tsx
  @navikt/core/react/src/stepper/Stepper.tsx
  @navikt/core/react/src/stepper/index.ts
  @navikt/core/react/src/stepper/stories/Example.tsx
  @navikt/core/react/src/stepper/stories/stepper.stories.mdx
  @navikt/core/react/src/stepper/stories/stepper.stories.tsx
Labels: new ✨, Ready for review

#1465 Tabs: ScrollButtons, Gjemmer scrollbar, overridable tag på Tab
  @navikt/core/css/tabs.css
  @navikt/core/react/src/tabs/Tab.tsx
  @navikt/core/react/src/tabs/TabList.tsx
Labels: Ready for review

#1451 [FIX] Tabs komponent
  @navikt/core/css/index.css
  @navikt/core/css/tabs.css
  @navikt/core/react/package.json
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/tabs/Tab.tsx
  @navikt/core/react/src/tabs/TabList.tsx
  @navikt/core/react/src/tabs/TabPanel.tsx
  @navikt/core/react/src/tabs/Tabs.stories.tsx
  @navikt/core/react/src/tabs/Tabs.tsx
  @navikt/core/react/src/tabs/index.ts
  yarn.lock
Labels: new ✨, Ready for review

#1470 [FIX] Pointer på Scrollbutton i Tabs
  @navikt/core/css/tabs.css
Labels: Ready for review

#1473 [FIX] type="button" på Readmore
  @navikt/core/react/src/read-more/ReadMore.tsx
Labels: Ready for review

#1462 [FIX] Tooltip komponent
  @navikt/core/css/index.css
  @navikt/core/css/tooltip.css
  @navikt/core/react/package.json
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/tooltip/Tooltip.tsx
  @navikt/core/react/src/tooltip/index.ts
  @navikt/core/react/src/tooltip/portal.tsx
  @navikt/core/react/src/tooltip/tooltip.stories.tsx
  @navikt/core/react/src/util/index.ts
  @navikt/core/tokens/src/index.js
  yarn.lock
Labels: new ✨, Ready for review
