Repository navikt/aksel, pull requests merged in 2022-10, with the labels that each got.

#1677 [FIX] :bug: Button disabled fungerte ikke med `as`-prop
  @navikt/core/css/button.css
  @navikt/core/react/src/button/Button.tsx
  @navikt/core/react/src/button/button.stories.tsx
Labels: bug 🐛, klar for gjennomgang 🔍

#1674 [FIX] ✨ Date/Monthpicker features
  @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
  @navikt/core/react/src/date/hooks/useDatepicker.tsx
  @navikt/core/react/src/date/hooks/useMonthPicker.tsx
  @navikt/core/react/src/date/hooks/useRangeDatepicker.tsx
  @navikt/core/react/src/date/monthpicker/monthpicker.stories.tsx
Labels: klar for gjennomgang 🔍, forespørsel 🥰

#1670 [fix] styling in shadow dom
  @navikt/core/css/accordion.css
  @navikt/core/css/alert.css
  @navikt/core/css/baseline/baseline.css
  @navikt/core/css/button.css
  @navikt/core/css/chat.css
  @navikt/core/css/content-container.css
  @navikt/core/css/form/confirmation-panel.css
  @navikt/core/css/form/error-summary.css
  @navikt/core/css/form/radio-checkbox.css
  @navikt/core/css/form/search.css
  @navikt/core/css/form/select.css
  @navikt/core/css/form/switch.css
  @navikt/core/css/form/text-field.css
  @navikt/core/css/form/textarea.css
  @navikt/core/css/guide-panel.css
  @navikt/core/css/help-text.css
  @navikt/core/css/link-panel.css
  @navikt/core/css/link.css
  @navikt/core/css/loader.css
  @navikt/core/css/modal.css
  @navikt/core/css/pagination.css
  @navikt/core/css/panel.css
  @navikt/core/css/popover.css
  @navikt/core/css/table.css
  @navikt/core/css/tag.css
  @navikt/core/css/toggle-group.css
  @navikt/core/css/typography.css
  @navikt/core/tokens/config.js
  @navikt/internal/css/dropdown.css
  @navikt/internal/css/header.css
  examples/shadow-dom/main.tsx
Labels: bug 🐛, tokens ⚙️, jobbes med 💨, forespørsel 🥰

#1679 [FIX] Justeringer Datepicker/Monthpicker
  @navikt/core/css/date.css
  @navikt/core/react/src/date/datepicker/DatePicker.tsx
  @navikt/core/react/src/date/datepicker/DatePickerStandalone.tsx
  @navikt/core/react/src/date/datepicker/DayButton.tsx
  @navikt/core/react/src/date/datepicker/Head.tsx
  @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
  @navikt/core/react/src/date/monthpicker/MonthButton.tsx
  @navikt/core/react/src/date/utils/parse-date.ts
Labels: diskusjon 🧐, design 🎨, universell utforming ⭐️, klar for gjennomgang 🔍

#1683 [FIX] :bug: Fikset css-kompilering for less, href med disabled
  @navikt/core/css/button.css
  @navikt/core/react/src/button/Button.tsx
  @navikt/core/react/src/button/button.stories.tsx
Labels: bug 🐛, jobbes med 💨

#1685 💄 Prettier-config for CSS
  @navikt/core/css/accordion.css
  @navikt/core/css/alert.css
  @navikt/core/css/button.css
  @navikt/core/css/chat.css
  @navikt/core/css/date.css
  @navikt/core/css/form/confirmation-panel.css
  @navikt/core/css/form/error-summary.css
  @navikt/core/css/form/radio-checkbox.css
  @navikt/core/css/form/search.css
  @navikt/core/css/form/select.css
  @navikt/core/css/form/switch.css
  @navikt/core/css/form/text-field.css
  @navikt/core/css/form/textarea.css
  @navikt/core/css/guide-panel.css
  @navikt/core/css/help-text.css
  @navikt/core/css/link-panel.css
  @navikt/core/css/loader.css
  @navikt/core/css/modal.css
  @navikt/core/css/pagination.css
  @navikt/core/css/panel.css
  @navikt/core/css/popover.css
  @navikt/core/css/read-more.css
  @navikt/core/css/stepper.css
  @navikt/core/css/table.css
  @navikt/core/css/tag.css
  @navikt/core/css/toggle-group.css
  @navikt/core/css/tooltip.css
  @navikt/core/css/typography.css
  @navikt/internal/css/dropdown.css
  @navikt/internal/css/header.css
  package.json
Labels: tokens ⚙️, klar for gjennomgang 🔍

#1688 [FIX] :bug: Fikset window-bug i jest
  @navikt/core/react/src/date/datepicker/datepicker.test.tsx
  @navikt/core/react/src/date/hooks/useDatepicker.tsx
  @navikt/core/react/src/date/hooks/useMonthPicker.tsx
  @navikt/core/react/src/date/hooks/useRangeDatepicker.tsx
  @navikt/core/react/src/util/useId.ts
Labels: klar for gjennomgang 🔍

#1689 [FIX] :bug: DatepickerInput hadde ikke error-markering
  @navikt/core/css/date.css
  @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
Labels: klar for gjennomgang 🔍

#1700 Repo-cleanup
  .storybook/main.js
  @navikt/codemod/transforms/v1.0.0/chat.ts
  @navikt/codemod/transforms/v1.0.0/pagination.ts
  @navikt/codemod/transforms/v1.0.0/tabs.ts
  @navikt/core/react/src/chat/Bubble.tsx
  @navikt/core/react/src/form/useFormField.ts
  @navikt/core/react/src/tabs/TabList.tsx
  @navikt/core/react/src/tooltip/portal.tsx
  @navikt/core/react/src/util/OverridableComponent.ts
  @navikt/core/react/src/util/mergeRefs.tsx
  @navikt/core/tokens/figma/file-styles.ts
  @navikt/icons/figma/index.ts
  package.json
  yarn.lock
Labels: klar for gjennomgang 🔍
