Repository navikt/aksel, pull requests merged in 2023-10, with the labels that each got.

#2376 :art: Mindre Helptext variant
  .changeset/wild-rice-arrive.md
  @navikt/core/css/help-text.css
  @navikt/core/react/src/help-text/HelpText.tsx
  @navikt/core/react/src/help-text/HelpTextIcon.tsx
Labels: klar for gjennomgang 🔍

#2391 :bug: Loader hadde legacyRef som ref-prop
  .changeset/heavy-shoes-pay.md
  @navikt/core/react/src/loader/Loader.tsx
  @navikt/core/react/src/loader/loader.stories.tsx
Labels: klar for gjennomgang 🔍

#2396 [aksel.nav.no] Refactor av amplitude-logging
  aksel.nav.no/website/components/SanityBlockContent.tsx
  aksel.nav.no/website/components/layout/footer/Footer.tsx
  aksel.nav.no/website/components/layout/header/Hamburger.tsx
  aksel.nav.no/website/components/layout/header/Header.tsx
  aksel.nav.no/website/components/layout/header/search/hooks/useSearch.ts
  aksel.nav.no/website/components/layout/header/search/providers/SearchLoggingProvider.tsx
  aksel.nav.no/website/components/layout/sidebar/Sidebar.tsx
  aksel.nav.no/website/components/sanity-modules/cards/ArtikkelCard.tsx
  aksel.nav.no/website/components/sanity-modules/cards/BloggCard.tsx
  aksel.nav.no/website/components/sanity-modules/cards/GodPraksisCard.tsx
  aksel.nav.no/website/components/sanity-modules/cards/GodPraksisCardSimple.tsx
  aksel.nav.no/website/components/sanity-modules/cards/InnholdsKort.tsx
  aksel.nav.no/website/components/sanity-modules/cards/RelatertInnhold.tsx
  aksel.nav.no/website/components/sanity-modules/frontpage-blocks/Card.tsx
  aksel.nav.no/website/components/sanity-modules/frontpage-blocks/Highlight.tsx
  aksel.nav.no/website/components/website-modules/AkselLink.tsx
  aksel.nav.no/website/components/website-modules/IntroCards.tsx
  aksel.nav.no/website/components/website-modules/feedback/index.tsx
  aksel.nav.no/website/components/website-modules/icon-page/Sidebar.tsx
  aksel.nav.no/website/components/website-modules/icon-page/TitleLinks.tsx
  aksel.nav.no/website/components/website-modules/utils/amplitude.tsx
  aksel.nav.no/website/components/website-modules/utils/index.ts
  aksel.nav.no/website/components/website-modules/utils/logging/event-tracking.ts
  aksel.nav.no/website/components/website-modules/utils/logging/events.ts
  aksel.nav.no/website/components/website-modules/utils/logging/index.ts
  aksel.nav.no/website/components/website-modules/utils/logging/useAmplitude.ts
  aksel.nav.no/website/components/website-modules/utils/util.ts
  aksel.nav.no/website/package.json
  aksel.nav.no/website/pages/404.tsx
  aksel.nav.no/website/pages/500.tsx
  aksel.nav.no/website/pages/_app.tsx
  aksel.nav.no/website/pages/_document.tsx
  aksel.nav.no/website/pages/komponenter/[...slug].tsx
  aksel.nav.no/website/pages/komponenter/index.tsx
  aksel.nav.no/website/tsconfig.json
  aksel.nav.no/website/tsconfig.tsnode.json
Labels: klar for gjennomgang 🔍

#2207 Autocomplete should keep upper-/lowercase from the word being autocompleted
  .changeset/early-colts-sneeze.md
  @navikt/core/react/src/form/combobox/FilteredOptions/filteredOptionsContext.tsx
  @navikt/core/react/src/form/combobox/Input/Input.tsx
  @navikt/core/react/src/form/combobox/combobox.stories.tsx
  yarn.lock
Labels: bug 🐛, klar for gjennomgang 🔍

#2426 :bug: Fikset dom-validering av Accordion
  .changeset/pink-suits-destroy.md
  @navikt/core/react/src/accordion/AccordionHeader.tsx
Labels: bug 🐛, klar for gjennomgang 🔍, komponenter 🧩
