Repository navikt/aksel, pull requests merged in 2023-08, with the labels that each got.

#2040 [Ny komponent] Stack, Spacer
  .changeset/cuddly-walls-thank.md
  @navikt/core/css/config/_mappings.js
  @navikt/core/css/index.css
  @navikt/core/css/stack.css
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/layout/stack/HStack.tsx
  @navikt/core/react/src/layout/stack/Spacer.tsx
  @navikt/core/react/src/layout/stack/Stack.tsx
  @navikt/core/react/src/layout/stack/VStack.tsx
  @navikt/core/react/src/layout/stack/index.ts
  @navikt/core/react/src/layout/stack/stack.stories.tsx
  @navikt/core/react/src/layout/utilities/css.ts
  aksel.nav.no/website/pages/eksempler/h-stack/align.tsx
  aksel.nav.no/website/pages/eksempler/h-stack/default.tsx
  aksel.nav.no/website/pages/eksempler/h-stack/justify.tsx
  aksel.nav.no/website/pages/eksempler/h-stack/nowrap.tsx
  aksel.nav.no/website/pages/eksempler/h-stack/responsive-gap.tsx
  aksel.nav.no/website/pages/eksempler/h-stack/spacer.tsx
  aksel.nav.no/website/pages/eksempler/header/default.tsx
  aksel.nav.no/website/pages/eksempler/header/description.tsx
  aksel.nav.no/website/pages/eksempler/header/home.tsx
  aksel.nav.no/website/pages/eksempler/header/menu.tsx
  aksel.nav.no/website/pages/eksempler/header/search.tsx
  aksel.nav.no/website/pages/eksempler/header/system.tsx
  aksel.nav.no/website/pages/eksempler/v-stack/align.tsx
  aksel.nav.no/website/pages/eksempler/v-stack/default.tsx
  aksel.nav.no/website/pages/eksempler/v-stack/justify.tsx
  aksel.nav.no/website/pages/eksempler/v-stack/responsive-gap.tsx
Labels: klar for gjennomgang 🔍, komponenter 🧩, beta 🧪

#2143 :bug: Forsøk på aria-live fix for button
  .changeset/brave-bottles-scream.md
  @navikt/core/react/src/button/Button.tsx
  @navikt/core/react/src/button/button.stories.tsx
  yarn.lock
Labels: bug 🐛, diskusjon 🧐, universell utforming ⭐️, klar for gjennomgang 🔍

#2144 Bugfix/combobox bugfixes and tweaks
  .changeset/wicked-crews-run.md
  @navikt/core/css/form/combobox.css
  @navikt/core/react/src/form/combobox/ComboboxWrapper.tsx
  @navikt/core/react/src/form/combobox/FilteredOptions/FilteredOptions.tsx
  @navikt/core/react/src/form/combobox/SelectedOptions/selectedOptionsContext.tsx
  @navikt/core/react/src/form/combobox/combobox.stories.tsx
  @navikt/core/react/src/form/combobox/types.ts
  aksel.nav.no/website/pages/eksempler/combobox/multi-select-controlled.tsx
  aksel.nav.no/website/pages/eksempler/combobox/multi-select-with-new-options.tsx
Labels: bug 🐛, design 🎨, dokumentasjon 📖, klar for gjennomgang 🔍

#2149 🎨 Oppdatert List-dokumentasjon, fikset bruk av ikoner med text
  .changeset/curly-grapes-scream.md
  @navikt/core/css/list.css
  aksel.nav.no/website/pages/eksempler/list/icons.tsx
  aksel.nav.no/website/pages/eksempler/list/nested.tsx
  aksel.nav.no/website/pages/eksempler/list/ordered.tsx
  aksel.nav.no/website/pages/eksempler/list/title.tsx
  aksel.nav.no/website/pages/eksempler/list/unordered.tsx
Labels: dokumentasjon 📖, klar for gjennomgang 🔍

#1838 [Primitives] HGrid
  .changeset/slow-frogs-eat.md
  @navikt/aksel-icons/figma-plugin/src/ui/utils.ts
  @navikt/core/css/hgrid.css
  @navikt/core/css/index.css
  @navikt/core/css/stack.css
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/layout/grid/HGrid.tsx
  @navikt/core/react/src/layout/grid/h-grid.stories.tsx
  @navikt/core/react/src/layout/grid/index.ts
  @navikt/core/react/src/layout/stack/Stack.tsx
  @navikt/core/react/src/layout/utilities/css.ts
  aksel.nav.no/website/components/website-modules/TOC.tsx
  aksel.nav.no/website/components/website-modules/icon-page/utils.ts
  aksel.nav.no/website/pages/eksempler/h-grid/columns-variants.tsx
  aksel.nav.no/website/pages/eksempler/h-grid/default.tsx
  aksel.nav.no/website/pages/eksempler/h-grid/responsive-columns.tsx
  aksel.nav.no/website/pages/eksempler/h-grid/responsive-gap.tsx
Labels: diskusjon 🧐, klar for gjennomgang 🔍

#2153 :truck: Markert gammelt grid som deprecated
  .changeset/great-cars-enjoy.md
  @navikt/core/css/config/_mappings.js
  @navikt/core/react/src/grid/Cell.tsx
  @navikt/core/react/src/grid/Grid.tsx
  @navikt/core/react/src/grid/index.ts
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/layout/content-container/ContentContainer.tsx
  @navikt/core/react/src/layout/content-container/index.ts
Labels: dokumentasjon 📖, klar for gjennomgang 🔍

#2159 :art: Fikset hardkodet border-radius i diverse komponenter
  .changeset/plenty-cobras-give.md
  @navikt/aksel-icons/figma-plugin/src/ui/app.css
  @navikt/core/css/date.css
  @navikt/core/css/form/combobox.css
  @navikt/core/css/toggle-group.css
  aksel.nav.no/website/styles/utilities.css
Labels: bug 🐛, klar for gjennomgang 🔍, komponenter 🧩

#2171 :art: Checkbox checkmark er nå SVG, ikke base64
  .changeset/soft-buttons-hope.md
  @navikt/core/css/form/radio-checkbox.css
  @navikt/core/react/src/form/checkbox/Checkbox.tsx
Labels: bug 🐛, klar for gjennomgang 🔍, komponenter 🧩

#2173 CopyButton prop for `iconPosition`
  .changeset/olive-steaks-hear.md
  @navikt/core/css/copybutton.css
  @navikt/core/react/src/copybutton/CopyButton.tsx
  @navikt/core/react/src/copybutton/copy-button.stories.tsx
Labels: klar for gjennomgang 🔍, komponenter 🧩

#2168 Oppdatert list: Small-variant, bugfixes
  .changeset/curvy-items-mate.md
  @navikt/core/css/list.css
  @navikt/core/react/src/list/List.tsx
  @navikt/core/react/src/list/ListItem.tsx
  @navikt/core/react/src/list/list.stories.tsx
  aksel.nav.no/website/pages/eksempler/list/icons.tsx
  aksel.nav.no/website/pages/eksempler/list/ordered.tsx
  aksel.nav.no/website/pages/eksempler/list/small.tsx
  aksel.nav.no/website/pages/eksempler/list/title.tsx
Labels: klar for gjennomgang 🔍

#2179 🐛 Alignet alert-ikon med tekst
  .changeset/wise-points-eat.md
  @navikt/core/css/alert.css
  @navikt/core/react/src/alert/Alert.tsx
  @navikt/core/react/src/alert/alert.stories.tsx
Labels: klar for gjennomgang 🔍, komponenter 🧩

#2178 La til large-size for Table, oppdatert expand-knapp
  .changeset/rotten-rules-greet.md
  .changeset/rotten-rules-greet2 copy.md
  .changeset/rotten-rules-greet2.md
  @navikt/core/css/table.css
  @navikt/core/react/src/table/DataCell.tsx
  @navikt/core/react/src/table/ExpandableRow.tsx
  @navikt/core/react/src/table/HeaderCell.tsx
  @navikt/core/react/src/table/Table.tsx
  @navikt/core/react/src/table/stories/table-expandable.stories.tsx
  @navikt/core/react/src/table/stories/table.stories.tsx
Labels: klar for gjennomgang 🔍

#2199 🐛 Checkmark, Confirmationpanel og Tokens patch
  .changeset/witty-cups-obey.md
  .changeset/witty-cups-obey2.md
  .changeset/witty-cups-obey3.md
  @navikt/core/css/form/radio-checkbox.css
  @navikt/core/react/src/form/ConfirmationPanel.tsx
  @navikt/core/react/src/form/stories/confirmation-panel.stories.tsx
  @navikt/core/tokens/docs.json
  @navikt/core/tokens/src/semantic-colors.json
Labels: klar for gjennomgang 🔍

#2200 🎨 Fikset mindre sanity-bugs
  aksel.nav.no/website/components/layout/footer/Footer.tsx
  aksel.nav.no/website/sanity/plugins/structure/index.tsx
  aksel.nav.no/website/sanity/sanity.config.tsx
  aksel.nav.no/website/sanity/util.tsx
Labels: klar for gjennomgang 🔍

#2204 :bug: Fikset token-naming for table-token
  .changeset/seven-ravens-happen.md
  @navikt/core/css/table.css
Labels: klar for gjennomgang 🔍

#2213 :bug: Input setter nå ikke `aria-controls` før popover åpnes
  .changeset/polite-clocks-join.md
  @navikt/core/react/src/date/DateInput.tsx
  yarn.lock
Labels: klar for gjennomgang 🔍

#2196 Storybook for Aksel-moduler, getting-started artikkel, ikoner
  .storybook/assets/aksel-thumbnail.png
  .storybook/assets/components.png
  .storybook/assets/setup.png
  .storybook/getting-started.stories.mdx
  .storybook/indexer.ts
  .storybook/intro.stories.mdx
  .storybook/layout.css
  .storybook/main.cjs
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview-head.html
  .storybook/preview.jsx
  .storybook/theme.js
  @navikt/aksel-icons/icons.stories.tsx
  @navikt/core/react/src/timeline/timeline.stories.tsx
  aksel.nav.no/website/.storybook/main.ts
  aksel.nav.no/website/.storybook/preview.ts
  aksel.nav.no/website/.storybook/utils.tsx
  aksel.nav.no/website/components/sanity-modules/Tips.stories.tsx
  aksel.nav.no/website/components/sanity-modules/token-view/categories/Semantic.tsx
  aksel.nav.no/website/components/sanity-modules/token-view/tokens.stories.tsx
  aksel.nav.no/website/tsconfig.json
  aksel.nav.no/website/tsconfig.tsnode.json
  package.json
  yarn.lock
Labels: klar for gjennomgang 🔍

#2154 Button setter role=button ved bruk av annen html-tag
  .changeset/eight-ads-develop.md
  @navikt/core/react/src/button/Button.tsx
  yarn.lock
Labels: diskusjon 🧐, universell utforming ⭐️, klar for gjennomgang 🔍

#2193 Mouse movements should "take over" from keyboard focus in Combobox dropdown list, and vice versa, acting like a native select.
  .changeset/tasty-llamas-talk.md
  @navikt/core/css/form/combobox.css
  @navikt/core/react/src/form/combobox/FilteredOptions/FilteredOptions.tsx
  @navikt/core/react/src/form/combobox/FilteredOptions/filteredOptionsContext.tsx
  @navikt/core/react/src/form/combobox/Input/Input.tsx
  @navikt/core/react/src/form/combobox/combobox.stories.tsx
Labels: bug 🐛, klar for gjennomgang 🔍
