Repository navikt/aksel, pull requests merged in 2024-01, with the labels that each got.

#2612 :bug: `Checkbox` nested i `CheckboxGroup` mister nå ikke padding
  .changeset/heavy-dolphins-hide.md
  @navikt/core/css/table.css
  @navikt/core/react/src/table/stories/table.stories.tsx
Labels: bug 🐛

#2613 [Table] DataCell og HeaderCell støtter nå `size`-prop for font-size
  .changeset/young-lizards-kick.md
  @navikt/core/react/src/table/DataCell.tsx
  @navikt/core/react/src/table/HeaderCell.tsx
  @navikt/core/react/src/table/stories/table.stories.tsx
Labels: bug 🐛, klar for gjennomgang 🔍

#2614 :bug: Togglegroup på ikonside overlapper ikke lengre
  aksel.nav.no/website/components/website-modules/icon-page/Page.tsx
Labels: bug 🐛, klar for gjennomgang 🔍

#2622 [V6] Deprecated Grid og ContentContainer
  .changeset/loud-boxes-drop.md
  @navikt/aksel-stylelint/src/deprecations.ts
  @navikt/core/css/content-container.css
  @navikt/core/css/grid.css
  @navikt/core/css/index.css
  @navikt/core/react/src/grid/Cell.tsx
  @navikt/core/react/src/grid/Grid.tsx
  @navikt/core/react/src/grid/grid.stories.tsx
  @navikt/core/react/src/grid/index.ts
  @navikt/core/react/src/index.ts
  @navikt/core/react/src/layout/content-container/ContentContainer.tsx
  @navikt/core/react/src/layout/content-container/index.ts
  v6-migration.md
Labels: Aksel-V6

#2619 :sparkles: createContext-utility
  @navikt/core/react/src/util/create-context.tsx
Labels: ignore-chromatic

#2636 :bug: Fikset deploy av Aksel.nav.no
  aksel.nav.no/nais-dev.yaml
  aksel.nav.no/nais-prod.yaml
Labels: ignore-chromatic

#2630 :zap: Er nå mulig å opt-out fra chromatic
  .github/workflows/chromatic.yml
Labels: ignore-chromatic

#2632 [V6] 1440px breakpoint
  .changeset/large-shrimps-brush.md
  @navikt/core/css/primitives/bleed.css
  @navikt/core/css/primitives/box.css
  @navikt/core/css/primitives/hgrid.css
  @navikt/core/css/primitives/responsive.css
  @navikt/core/css/primitives/stack.css
  @navikt/core/react/src/layout/bleed/Bleed.tsx
  @navikt/core/react/src/layout/box/Box.stories.tsx
  @navikt/core/react/src/layout/sidemal-test/navno-sidemal.stories.mdx
  @navikt/core/react/src/layout/sidemal-test/navno-sidemal.stories.tsx
  @navikt/core/react/src/layout/utilities/types.ts
  @navikt/core/tokens/docs.json
  @navikt/core/tokens/src/index.js
  v6-migration.md
Labels: Aksel-V6, ignore-chromatic

#2637 [V6] Fjernet z-index-modal token
  .changeset/tall-turtles-flow.md
  @navikt/core/tokens/docs.json
  @navikt/core/tokens/src/index.js
  v6-migration.md
Labels: Aksel-V6, ignore-chromatic

#2642 [V6] ErrorSummary magic
  .changeset/gold-pumas-cheat.md
  @navikt/core/css/form/error-summary.css
  @navikt/core/react/src/form/error-summary/ErrorSummary.tsx
  @navikt/core/react/src/form/error-summary/ErrorSummaryItem.tsx
  @navikt/core/react/src/form/error-summary/error-summary.stories.tsx
  aksel.nav.no/website/pages/eksempler/errorsummary/setting-focus.tsx
  v6-migration.md
Labels: Aksel-V6, ignore-chromatic

#2661 Oppgradering av pakker i figma-plugin
  .storybook/main.mts
  @navikt/aksel-icons/figma-plugin/package.json
  @navikt/aksel-icons/figma-plugin/src/ui/App.tsx
  aksel.nav.no/website/components/types/search.ts
  aksel.nav.no/website/components/website-modules/search/utils/format-result.ts
  aksel.nav.no/website/components/website-modules/search/utils/group-results.ts
  aksel.nav.no/website/components/website-modules/search/utils/highlighter.tsx
  aksel.nav.no/website/package.json
  package.json
  yarn.lock
Labels: ignore-chromatic

#2652 [tailwind] MaxWidth-token brukt for text i tailwind
  .changeset/twenty-planes-fry.md
  @navikt/core/tailwind/src/getMaxWidth.ts
  @navikt/core/tailwind/src/index.ts
Labels: ignore-chromatic

#2672 LocationPin-ikon
  .changeset/afraid-oranges-grow.md
  @navikt/aksel-icons/icons/LocationPin.svg
  @navikt/aksel-icons/icons/LocationPin.yml
  @navikt/aksel-icons/icons/LocationPinFill.svg
  @navikt/aksel-icons/icons/LocationPinFill.yml
Labels: ignore-chromatic

#2680 🔴 Støtte for høykontrast i komponenter
  .changeset/metal-ads-love.md
  @navikt/core/css/accordion.css
  @navikt/core/css/alert.css
  @navikt/core/css/button.css
  @navikt/core/css/chat.css
  @navikt/core/css/chips.css
  @navikt/core/css/copybutton.css
  @navikt/core/css/dropdown.css
  @navikt/core/css/expansioncard.css
  @navikt/core/css/form/combobox.css
  @navikt/core/css/form/confirmation-panel.css
  @navikt/core/css/form/fieldset.css
  @navikt/core/css/form/form.css
  @navikt/core/css/form/radio-checkbox.css
  @navikt/core/css/form/search.css
  @navikt/core/css/form/select.css
  @navikt/core/css/form/switch.css
  @navikt/core/css/form/text-field.css
  @navikt/core/css/form/textarea.css
  @navikt/core/css/help-text.css
  @navikt/core/css/internalheader.css
  @navikt/core/css/link-panel.css
  @navikt/core/css/link.css
  @navikt/core/css/loader.css
  @navikt/core/css/modal.css
  @navikt/core/css/popover.css
  @navikt/core/css/read-more.css
  @navikt/core/css/skeleton.css
  @navikt/core/css/stepper.css
  @navikt/core/css/table.css
  @navikt/core/css/tabs.css
  @navikt/core/css/tag.css
  @navikt/core/css/timeline.css
  @navikt/core/css/toggle-group.css
  @navikt/core/css/tooltip.css
Labels: bug 🐛, design 🎨, forespørsel 🥰

#2682 🐛 Sentrering av checkmark i Checkbox
  .changeset/famous-peas-invent.md
  @navikt/core/css/form/radio-checkbox.css
Labels: bug 🐛, klar for gjennomgang 🔍, komponenter 🧩
