Repository navikt/aksel, pull requests merged in 2024-08, with the labels that each got.

#3053 Combobox: Pressing Escape in while focusing a Combobox inside a Modal will close the Modal
  .changeset/silly-walls-sip.md
  @navikt/core/react/src/form/combobox/Input/Input.tsx
  @navikt/core/react/src/form/combobox/combobox.stories.tsx
Labels: diskusjon 🧐, klar for gjennomgang 🔍

#3029 feat: Added stale-issue handling
  .github/workflows/stale.yml
Labels: klar for gjennomgang 🔍

#3072 New icons SplitHorizontal and SplitVertical
  .changeset/gold-parents-march.md
  @navikt/aksel-icons/icons/SplitHorizontal.svg
  @navikt/aksel-icons/icons/SplitHorizontal.yml
  @navikt/aksel-icons/icons/SplitHorizontalFill.svg
  @navikt/aksel-icons/icons/SplitHorizontalFill.yml
  @navikt/aksel-icons/icons/SplitVertical.svg
  @navikt/aksel-icons/icons/SplitVertical.yml
  @navikt/aksel-icons/icons/SplitVerticalFill.svg
  @navikt/aksel-icons/icons/SplitVerticalFill.yml
Labels: klar for gjennomgang 🔍

#2906 FloatingMenu component
  @navikt/core/react/src/overlays/floating-menu/Menu.stories.tsx
  @navikt/core/react/src/overlays/floating-menu/Menu.tsx
  @navikt/core/react/src/overlays/floating-menu/parts/FocusScope.tsx
  @navikt/core/react/src/overlays/floating-menu/parts/RovingFocus.tsx
  @navikt/core/react/src/overlays/floating-menu/parts/SlottedDivElement.tsx
  @navikt/core/react/src/util/composeEventHandlers.ts
  yarn.lock
Labels: klar for gjennomgang 🔍

#3068 feat: Order GP-articles based on last verified, not publish date
  aksel.nav.no/website/components/layout/god-praksis-page/ArticleSections.tsx
  aksel.nav.no/website/components/layout/god-praksis-page/cards/GpArticleCard.stories.tsx
  aksel.nav.no/website/components/layout/god-praksis-page/cards/GpArticleCard.tsx
  aksel.nav.no/website/components/layout/god-praksis-page/interface.ts
  aksel.nav.no/website/pages/god-praksis/[slug].tsx
Labels: klar for gjennomgang 🔍

#3086 Changed "design" category to "brand" in "Grunnleggende"
  aksel.nav.no/website/sanity/config.ts
Labels: klar for gjennomgang 🔍

#3082 Primitives: Added `gridColumn`-prop for more grid alignment control
  .changeset/metal-days-cough.md
  @navikt/core/css/primitives/base.css
  @navikt/core/react/src/layout/base/BasePrimitive.stories.tsx
  @navikt/core/react/src/layout/base/BasePrimitive.tsx
Labels: klar for gjennomgang 🔍

#3092 History i now kept when navigating filters on god-praksis pages
  aksel.nav.no/website/components/layout/god-praksis-page/chipnavigation/GpChipRow.tsx
Labels: klar for gjennomgang 🔍

#3095 Table: Fixed background clipping when using ExpandableRow
  .changeset/modern-items-leave.md
  @navikt/core/css/table.css
  @navikt/core/react/src/table/ExpandableRow.tsx
Labels: klar for gjennomgang 🔍

#3114 Font naming and location preload fix
  .changeset/tender-donuts-punch.md
  @navikt/core/css/baseline/fonts.css
  fonts/README.md
  fonts/SourceSans3-italic-cyrillic.woff2
  fonts/SourceSans3-italic-cyrillic_ext.woff2
  fonts/SourceSans3-italic-latin_ext.woff2
  fonts/SourceSans3-italic.woff2
  fonts/SourceSans3-normal-cyrillic.woff2
  fonts/SourceSans3-normal-cyrillic_ext.woff2
  fonts/SourceSans3-normal-latin_ext.woff2
  fonts/SourceSans3-normal.woff2
  fonts/SourceSans3/italic-cyrillic-ext.woff2
  fonts/SourceSans3/italic-cyrillic.woff2
  fonts/SourceSans3/italic-latin-ext.woff2
  fonts/SourceSans3/italic-latin.woff2
  fonts/SourceSans3/normal-cyrillic-ext.woff2
  fonts/SourceSans3/normal-cyrillic.woff2
  fonts/SourceSans3/normal-latin-ext.woff2
  fonts/SourceSans3/normal-latin.woff2
Labels: klar for gjennomgang 🔍

#3094 Tooltip labeling
  .changeset/little-files-cough.md
  @navikt/core/react/src/tooltip/Tooltip.tsx
  @navikt/core/react/src/tooltip/tooltip.stories.tsx
  aksel.nav.no/website/pages/eksempler/togglegroup/with-tooltip.tsx
  aksel.nav.no/website/pages/eksempler/tooltip/demo.tsx
  aksel.nav.no/website/pages/eksempler/tooltip/labeling.tsx
  aksel.nav.no/website/pages/eksempler/tooltip/no-arrow.tsx
  aksel.nav.no/website/pages/eksempler/tooltip/placement.tsx
  aksel.nav.no/website/pages/eksempler/tooltip/with-shortcuts.tsx
  aksel.nav.no/website/scripts/update-examples/parts/extract-args.ts
  aksel.nav.no/website/scripts/update-examples/parts/extract-metadata.ts
Labels: diskusjon 🧐, klar for gjennomgang 🔍, Aksel-V7
